PetStore/Controllers/FoodsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PetStore.Data;
using PetStore.Models;

namespace PetStore.Controllers
{
    public class FoodsController : Controller
    {
        private readonly PetStoreContext _context;

        public FoodsController(PetStoreContext context)
        {
            _context = context;
        }

        // GET: Foods
        [Authorize]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Food.ToListAsync());
        }

        public dynamic GetAll()
        {
            return _context.Food.Select(food => new { food.Price }).ToList();
        }

        public async Task<IActionResult> Search(string name, string description, int price)
        {
            var searchResult = _context.Food.Where(a => (a.Name.Contains(name) || name == null) && (a.Price <= price) && 
            (a.Description.Contains(description) || description == null));
            return View("Index", await searchResult.ToListAsync());
        }

        // GET: Foods/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var food = await _context.Food
                .FirstOrDefaultAsync(m => m.Id == id);
            if (food == null)
            {
                return NotFound();
            }

            return View(food);
        }

        // GET: Foods/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Foods/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Id,Price,Name,Description,ImageFile")] Food food)
        {
            if (ModelState.IsValid)
            {
                using (MemoryStream ms = new MemoryStream())
                {
                    food.ImageFile.CopyTo(ms);
                    food.Image = ms.ToArray();
                }

                _context.Add(food);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(food);
        }

        // GET: Foods/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var food = await _context.Food.FindAsync(id);
            if (food == null)
            {
                return NotFound();
            }
            return View(food);
        }

        // POST: Foods/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Price,Name,Description,ImageFile,Image")] Food food)
        {
            if (id != food.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    using (MemoryStream ms = new MemoryStream())
                    {
                        food.ImageFile.CopyTo(ms);
                        food.Image = ms.ToArray();
                    }

                    _context.Update(food);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FoodExists(food.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(food);
        }

        // GET: Foods/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var food = await _context.Food
                .FirstOrDefaultAsync(m => m.Id == id);
            if (food == null)
            {
                return NotFound();
            }

            return View(food);
        }

        // POST: Foods/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var food = await _context.Food.FindAsync(id);
            _context.Food.Remove(food);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FoodExists(int id)
        {
            return _context.Food.Any(e => e.Id == id);
        }
    }
}

PetStore/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PetStore.Data;
using PetStore.Helpers;
using PetStore.Models;

namespace PetStore.Controllers
{
    public class UsersController : Controller
    {
        private readonly PetStoreContext _context;

        public UsersController(PetStoreContext context)
        {
            _context = context;
        }

        // GET: Users
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.User.ToListAsync());
        }

        public async Task<IActionResult> Search(string fullName)
        {

            var searchResult = from user in _context.User
                    where (user.FullName.Contains(fullName) || fullName == null)
                    orderby user.FullName descending
                    select user;
            return View("Index", await searchResult.ToListAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.UserName == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }


        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(bool isManager, [Bind("UserName,Address,Email,Password,FullName")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                if (isManager) _context.Add(new Manager { EmployeeId = user.UserName, User = user });

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User.FindAsync(id);

            var m = _context.Manager.FirstOrDefault(manager => manager.UserName == user.UserName);
            user.Manager = m;

            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string UserName, [Bind("UserName,Address,Email,Password,FullName")] User user, bool isManager)
        {
            if (UserName != user.UserName)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    Manager m = _context.Manager.FirstOrDefault(m => m.UserName == user.UserName);
                    bool isCurrentlyManager = m != null;


                    if (isManager && !isCurrentlyManager) { _context.Add(new Manager { EmployeeId = user.UserName, User = user });
                       
                    }
                    
                    else if(isCurrentlyManager && !isManager)
                    {
                        _context.Remove(m);
                    }

                    await _context.SaveChangesAsync();

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.UserName))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.UserName == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string UserName)
        {
            var user = await _context.User.FindAsync(UserName);
            _context.User.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(string id)
        {
            return _context.User.Any(e => e.UserName == id);
        }

        // GET: Users/Register
        public IActionResult Register()
        {
            return View();
        }

        // POST: Users/Register
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register([Bind("UserName,Address,Email,Password,FullName")] User user)
        {
            if (ModelState.IsValid)
            {
                User foundUser = _context.User.FirstOrDefault(u => u.UserName == user.UserName);

                if (foundUser == null)
                {
                    _context.Add(user);
                    await _context.SaveChangesAsync();

                    var foundUsers = from u in _context.User
                                     where u.UserName == user.UserName && u.Password == user.Password
                                     select u;

                    this.Signin(foundUsers.First());
                    return RedirectToAction(nameof(Index), "Home");
                } else {
                    ViewData["Error"] = "UserName taken";
                }
            }
            return View(user);
        }


        // GET: Users/LogIn
        public IActionResult LogIn()
        {
            return View();
        }

        // POST: Users/LogIn
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LogIn([Bind("UserName,Password")] User user)
        {
            if (ModelState.IsValid)
            {
                var foundUsers = from u in _context.User
                                 where u.UserName == user.UserName && u.Password == user.Password
                                 select u;

                if (foundUsers.Count() != 0)
                {
                 /*   HttpContext.Session.SetString("userName", foundUsers.First().UserName);
                    HttpContext.Session.SetString("password", foundUsers.First().Password);*/

                    var manager = _context.Manager.FirstOrDefault(u => u.EmployeeId == user.UserName);

                    User x = foundUsers.First();
                    x.Manager = manager;
                    this.Signin(x);

                    return RedirectToAction(nameof(Index), "Home");
                }
                else
                {
                    ViewData["Error"] = "UserName and/or Password are incorrect";
                }
            }
            return View(user);
        }

        // Log Out
        public async Task<IActionResult> Logout()
        {

            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            // reset cart
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", null);
            return RedirectToAction("Login");
        }

        private async void Signin(User account)
        {
            var claims = new List<Claim> {
                new Claim(ClaimTypes.Name, account.UserName),
                new Claim(ClaimTypes.Role, account.Manager != null ? "Admin" : "Client")
            };

            var claimsIdentity = new ClaimsIdentity(
                claims, 
                CookieAuthenticationDefaults.AuthenticationScheme
                );

            var authProperties = new AuthenticationProperties
            {
                /*ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(10)*/
            };
            
            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme, 
                new ClaimsPrincipal(claimsIdentity),
                authProperties);
        }

        // GET: Users/AccessDenied
        public IActionResult AccessDenied()
        {
            return View();
        }
    }
        
}

PetStore/Views/Admins/Index.cshtml
@{
    ViewData["Title"] = "Admin";
}

<link href="~/css/general.css" rel="stylesheet" />

<div class="px-5 py-5 mt-4">
    <div class="row">
        <div class="col-md-8 order-md-1">
            <div class="mb-4">
                <h4 style="color: #0c5460">Pet Store Managment</h4>
            </div>
            <div>
                <a class="btn btn-secondary btn-lg natural-btn mb-2" asp-controller="Users" asp-action="Index">Users</a>
                <span class="badge badge-info green-blue-backgroung-color">@ViewBag.UsersCount</span>
            </div>
            <div>
                <a class="btn btn-secondary btn-lg natural-btn mb-2" asp-controller="StoreBranches" asp-action="Index">Stores Branches</a>
                <span class="badge badge-info green-blue-backgroung-color">@ViewBag.StoreBranchesCount</span>
            </div>
            <div>
                <a class="btn btn-secondary btn-lg natural-btn mb-2" asp-controller="Orders" asp-action="Index">Orders</a>
                <span class="badge badge-info green-blue-backgroung-color">@ViewBag.OrdersCount</span>
            </div>
            <div>
                <a class="btn btn-secondary btn-lg natural-btn mb-2" asp-controller="Animals" asp-action="Index">Animals</a>
                <span class="badge badge-info green-blue-backgroung-color">@ViewBag.AnimalsCount</span>
            </div>
            <div>
                <a class="btn btn-secondary btn-lg natural-btn mb-2" asp-controller="Foods" asp-action="Index">Foods</a>
                <span class="badge badge-info green-blue-backgroung-color">@ViewBag.FoodsCount</span>
            </div>

            <div>
                <a class="btn btn-secondary btn-lg natural-btn mb-2" asp-controller="AnimalTypes" asp-action="Index">AnimalTypes</a>
                <span class="badge badge-info green-blue-backgroung-color">@ViewBag.AnimalTypesCount</span>
            </div>
        </div>
    </div>
</div>

PetStore/Views/Admins/Statistics.cshtml
@{ ViewData["Title"] = "Statistics"; }


<div class="py-5 mt-5 container">
    <div class="row justify-content-center mb-4">
        <button type="button" class="btn btn-dark col-4 mr-3" id="showAnimal">
            Average price of animal by type
        </button>
        <button type="button" class="btn btn-dark col-4 ml-3" id="showBranch">
            Orders amount by store branch
        </button>
    </div>

    <style type="text/css">
        .animalsStatistics {
            display: none;
        }

        .branchesStatistics {
            display: none;
        }
    </style>

    <div class="stat-chart animalsStatistics row justify-content-center" style=" text-align: center;" id="animals">
        @*        <h3>Average price of animal by type</h3><br />
        *@        <h5>This chart compares animal types according to their average price.</h5>
        <div id="tooltip-bar"></div>
        <div class="bar"></div>
    </div>
    <div class="stat-chart branchesStatistics row justify-content-center" style=" text-align: center;" id="branches">
        @*        <h3>Orders amount by store branch</h3><br />
        *@        <h5>This pie diagram represents the distribution of orders according to their animal's storebranch.</h5>
        <div id="tooltip-pie"></div>
        <div class="pie"></div>
    </div>

    <script src="https://d3js.org/d3.v5.min.js"></script>

    <script>

    function drawBarChart(data) {
        // Define css for the graph.
        var margin = { top: 20, right: 20, bottom: 30, left: 40 },
            width = 960 - margin.left - margin.right,
            height = 600 - margin.top - margin.bottom;

        // Set the ranges of scales.
        var x = d3.scaleBand()
            .range([0, width])
            .padding(0.1);
        var y = d3.scaleLinear()
            .range([height, 0]);

        // Get 10 colors from palette.
        var color = d3.schemeCategory10;

        // Append the svg object to the body of the page.
        // Append a 'group' element to 'svg'.
        // Moves the 'group' element to the top left margin.
        var svg = d3.select(".bar").append("svg")
            .attr("width", width + margin.left + margin.right)
            .attr("height", height + margin.top + margin.bottom)
            .append("g")
            .attr("transform",
            "translate(" + margin.left + "," + margin.top + ")");

        // Scaling the ranges for the data.
        x.domain(data.map(function (d) { return d.animalType; }));
        y.domain([0, d3.max(data, function (d) { return d.avg; })]);

        // Append the rectangles for the bars.
        svg.selectAll(".bar")
            .data(data)
            .enter().append("rect")
            .attr("class", "bar")
            .attr("x", function (d) { return x(d.animalType); })
            .attr("width", x.bandwidth())
            .attr("y", function (d) { return y(d.avg); })
            .attr("height", function (d) { return height - y(d.avg); })
            .attr('fill', function (d, i) { return color[i]; })
            .on("mouseover", function (d) {
                d3.select('#tooltip-bar')
                .style("visibility", "visible")
                 .text('type ' + d.animalType + ' avg: ' + d.avg);
            })
            .on("mousemove", function () {
                d3.select('#tooltip-bar')
                    .style("top", (event.pageY - 10) + "px")
                    .style("left", (event.pageX + 10) + "px");
            })
            .on("mouseout", function () {
                d3.select('#tooltip-bar')
                    .style("visibility", "hidden");
            });

        // Add x Axis
        svg.append("g")
            .attr("transform", "translate(0," + height + ")")
            .call(d3.axisBottom(x));

        // Add y Axis
        svg.append("g")
            .attr("class", "y axis")
            .call(d3.axisLeft(y).ticks(3))
            .append("text")
            .attr("transform", "rotate(-90)")
            .attr("y", 6)
            .attr("dy", "-35px")
            .text("Avg price");
    }

    function drawPieChart(data) {

        // Defing height and width to the pie.
        var h = 300;
        var w = 300;

        // Define inner and outer radius for the pie.
        var innerRadius = w / 4;
        var outerRadius = w / 2;

        // Generate pie as function to be called.
        var pie = d3.pie().value(function (d) {
            return d.ordersCount;
        });

        // Creating color scheme, generates 10 scale ordnal.
        var color = d3.schemeCategory10;

        // Will be used to generate the path attribute.
        var arc = d3.arc()
            .innerRadius(innerRadius)
            .outerRadius(outerRadius);

        // Create the svg canvas.
        var svg = d3.select('.pie')
            .append('svg')
            .attr('width', w)
            .attr('height', h);

        // Set up groups of arcs.
        var arcs = svg.selectAll('g.arc')
            .data(pie(data))
            .enter()
            .append('g')
            .attr('class', 'arc')
            .attr('transform', 'translate(' + outerRadius + ', ' + outerRadius + ')')
            .on("mouseover", function (d) {
                d3.select('#tooltip-pie')
                    .style("visibility", "visible")
                    .text('Orders count of store branch: ' + d.data.storeBranchName);
            })
            .on("mousemove", function () {
                d3.select('#tooltip-pie')
                    .style("top", (event.pageY - 10) + "px")
                    .style("left", (event.pageX + 10) + "px");
            })
            .on("mouseout", function () {
                d3.select('#tooltip-pie')
                    .style("visibility", "hidden");
            });

        // Add path to groups.
        arcs.append('path')
            .attr('fill', function (d, i) {
                return color[i];
            })
            .attr('d', arc);

        // Append text.
        arcs.append('text')
            .attr("transform", function (d) {
                return "translate(" + arc.centroid(d) + ")"; // Getting the center point of the shape.
            })
            .attr("text-anchor", "middle")
            .text(function (d) {
                return d.value;
            });

    }

    // Draws the graphs according to the data from the controller.
    drawBarChart(JSON.parse('@Html.Raw(ViewBag.avgPriceByTypeData)'));
    drawPieChart(JSON.parse('@Html.Raw(ViewBag.ordersByStoreBranchData)'));
    </script>
    <script>
        document.getElementById('showAnimal').onclick = function () {
            $(".animalsStatistics").css("display", "block");
            $(".branchesStatistics").css("display", "none");
        }

        document.getElementById('showBranch').onclick = function () {
            $(".branchesStatistics").css("display", "block");
            $(".animalsStatistics").css("display", "none");
        }
    </script>
</div>