PetStore/Controllers/AdminsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PetStore.Data;
using PetStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PetStore.Controllers
{
    public class AdminsController : Controller { 

        private readonly PetStoreContext _context;

    public AdminsController(PetStoreContext context)
    {
        _context = context;
    }
    
        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            ViewData["StoreBranchesCount"] =  _context.StoreBranch.ToList().Count();
            ViewData["AnimalsCount"] = _context.Animal.ToList().Count();
            ViewData["FoodsCount"] = _context.Food.ToList().Count();
            ViewData["OrdersCount"] = _context.Order.ToList().Count();
            ViewData["UsersCount"] = _context.User.ToList().Count();
            ViewData["AnimalTypesCount"] = _context.AnimalType.ToList().Count();


            return View();
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Statistics()
        {
            var avgPriceByType = _context.Animal.GroupBy(a => a.TypeId).Select(c => new { animalType = (c.Key), avg = c.Sum(a=> a.Price)/c.Count() }).ToList();
            var avgPriceByTypeData = JsonConvert.SerializeObject(avgPriceByType);
            ViewData["avgPriceByTypeData"] = avgPriceByTypeData;


            var ordersByStoreBranches = _context.Animal
                .Join(_context.StoreBranch,
                        animal => animal.StoreBranchId,
                        storeBranch => storeBranch.Id,
                          (animal, storeBranch) => new
                          {
                              animalId = animal.Id,
                              storeBranchId = animal.StoreBranchId,
                              storeBranchName = storeBranch.Name,
                              orderId = animal.OrderId
                          })
                .ToList()
                .GroupBy(a => a.storeBranchId)
                .Select(c => new { storeBranchName = c.First(i=> i.storeBranchId == c.Key).storeBranchName, 
                                   ordersCount = c.Where(i => i.orderId != null).GroupBy(i => i.orderId).Count() })
                .ToList();

            

            var ordersByStoreBranchData = JsonConvert.SerializeObject(ordersByStoreBranches);
            ViewData["ordersByStoreBranchData"] = ordersByStoreBranchData;  

            return View();
            
           
        }
    }
}

PetStore/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using PetStore.Helpers;
using PetStore.Data;
using PetStore.Models;
using Microsoft.AspNetCore.Http;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace PetStore.Controllers
{
    public class CartController : Controller
    {
        private readonly PetStoreContext _context;

        public CartController(PetStoreContext context)
        {
            _context = context;
        }

        [Authorize]
        public IActionResult Index()
        {
            List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");

            ViewBag.cart = cart;
            if (cart != null)
            {
                ViewBag.countProducts = cart.Count();
                ViewBag.total = calculateSum();
            } else
            {
                ViewBag.countProducts = 0;
                ViewBag.total = 0;
            }

            return View();
        }

        [Authorize]
        public IActionResult Add(int id, CartItem.CartItemType type)
        {
            if (SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart") == null)
            {
                List<CartItem> cart = new List<CartItem>();
                cart.Add(new CartItem { Product = getProductData(id, type), Quantity = 1, Type = type });
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else
            {
                List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
                int index = isExistInCart(id, type);
                if (index != -1)
                {
                    if(type != CartItem.CartItemType.ANIMAL)
                    {
                        cart[index].Quantity++;
                    }
                }
                else
                {
                    cart.Add(new CartItem { Product = getProductData(id, type), Type = type, Quantity = 1 });
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            return RedirectToAction(nameof(Index));
        }


        [Authorize]
        public IActionResult Remove(int id, CartItem.CartItemType type)
        {
            List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
            int index = isExistInCart(id, type);
            cart.RemoveAt(index);

            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        public IActionResult Reduce(int id, CartItem.CartItemType type)
        {
            List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
            int index = isExistInCart(id, type);
            cart[index].Quantity--;
            if (cart[index].Quantity == 0)
            {
                cart.RemoveAt(index);
            }
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToAction(nameof(Index));
        }


        private int isExistInCart(int id, CartItem.CartItemType type)
        {
            List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Product.Id == id && cart[i].Type.Equals(type))
                {
                    return i;
                }
            }
            return -1;
        }


        private double calculateSum()
        {
            double sum = 0;
            List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
            cart.ForEach(item =>
            {
                sum += item.Product.Price * item.Quantity;
            });


            return sum;
        }
        private CartItem.ProductData getProductData(int id, CartItem.CartItemType type)
        {
            if (type == CartItem.CartItemType.ANIMAL)
            {
                Animal animal = _context.Animal.First(a => a.Id == id);
                if (animal != null)
                {
                    return new CartItem.ProductData { Id = animal.Id, Name = animal.Name, Image = animal.Image, Price = animal.Price, Description = animal.Description  };
                }
            }
            else if (type == CartItem.CartItemType.FOOD)
            {
                Food food = _context.Food.First(f => f.Id == id);
                if (food != null)
                {
                    return new CartItem.ProductData { Id = food.Id, Name = food.Name, Image = food.Image, Price = food.Price, Description = food.Description }; ;
                }
            }

            return null;
        }
    }
}

PetStore/Controllers/FoodsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PetStore.Data;
using PetStore.Models;

namespace PetStore.Controllers
{
    public class FoodsController : Controller
    {
        private readonly PetStoreContext _context;

        public FoodsController(PetStoreContext context)
        {
            _context = context;
        }

        // GET: Foods
        [Authorize]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Food.ToListAsync());
        }

        public dynamic GetAll()
        {
            return _context.Food.Select(food => new { food.Price }).ToList();
        }

        public async Task<IActionResult> Search(string name, string description, int price)
        {
            var searchResult = _context.Food.Where(a => (a.Name.Contains(name) || name == null) && (a.Price <= price) && 
            (a.Description.Contains(description) || description == null));
            return View("Index", await searchResult.ToListAsync());
        }

        // GET: Foods/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var food = await _context.Food
                .FirstOrDefaultAsync(m => m.Id == id);
            if (food == null)
            {
                return NotFound();
            }

            return View(food);
        }

        // GET: Foods/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Foods/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Id,Price,Name,Description,ImageFile")] Food food)
        {
            if (ModelState.IsValid)
            {
                using (MemoryStream ms = new MemoryStream())
                {
                    food.ImageFile.CopyTo(ms);
                    food.Image = ms.ToArray();
                }

                _context.Add(food);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(food);
        }

        // GET: Foods/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var food = await _context.Food.FindAsync(id);
            if (food == null)
            {
                return NotFound();
            }
            return View(food);
        }

        // POST: Foods/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Price,Name,Description,ImageFile,Image")] Food food)
        {
            if (id != food.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    using (MemoryStream ms = new MemoryStream())
                    {
                        food.ImageFile.CopyTo(ms);
                        food.Image = ms.ToArray();
                    }

                    _context.Update(food);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FoodExists(food.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(food);
        }

        // GET: Foods/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var food = await _context.Food
                .FirstOrDefaultAsync(m => m.Id == id);
            if (food == null)
            {
                return NotFound();
            }

            return View(food);
        }

        // POST: Foods/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var food = await _context.Food.FindAsync(id);
            _context.Food.Remove(food);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FoodExists(int id)
        {
            return _context.Food.Any(e => e.Id == id);
        }
    }
}

PetStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PetStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="margin-bottom: 0px!important">
    <style type="text/css">
        body {
            background-image: linear-gradient( rgba(255, 255, 255, 0.7), rgba(255, 255, 255, 0.7) ), url('../../Images/JungleBackground.jpg');
            color: #273825;
        }
    </style>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom fixed-top" style="overflow-y: hidden;">
            <div class="container">
                <a class="navbar-brand d-flex" asp-area="" asp-controller="Home" asp-action="Index">
                    <canvas id="viewport" width="30" height="30"></canvas>
                </a>
                <a>
                    @if (Context.User != null && Context.User.Claims != null && Context.User.Claims.Count() > 0)
                    {
                        <a class="navbar-brand" style="font-size: 1rem;">
                            Hello @Context.User.Identity.Name :)
                        </a>
                    }
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row">
                    <ul class="navbar-nav flex-grow-1">
                        @if (Context.User != null && Context.User.Claims != null && Context.User.Claims.Count() > 0)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Logout">Log out</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Login">Log in</a>
                            </li>
                        }
                    </ul>
                    @if (Context.User != null && Context.User.Claims != null && Context.User.Claims.Count() > 0)
                    {
                        <ul class="nav navbar-nav navbar-right">

                            @if (Context.User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admins" asp-action="Index">Pet Store Managment</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admins" asp-action="Statistics">Statistics</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Foods" asp-action="Index">Food</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Animals" asp-action="Index">Animals</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">Cart</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Orders</a>
                                </li>
                            }
                        </ul>
                    }

                </div>
            </div>
        </nav>
    </header>
     <main role="main" class="pb-5">
            @RenderBody()
    </main>
    </div>
     <footer class="fixed-bottom bg-white" style="display: flex; justify-content: flex-start">
         <p style="margin: 0 0 0 15px">By: Illi Malachi, Noam Barda, Shahar Anati</p>
     </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

PetStore/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PetStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>